package com.mass3d.common;

public enum DataDimensionItemType {
  DATA_ELEMENT,
  INDICATOR,
  DATA_ELEMENT_OPERAND,
  REPORTING_RATE,
  PROGRAM_INDICATOR,
  PROGRAM_DATA_ELEMENT,
  PROGRAM_ATTRIBUTE,
  VALIDATION_RULE
}
