package com.mass3d.system.util;

import java.util.Base64;

/**
 * Utility class for encoding and decoding operations.
 *
 */
public class CodecUtils {

  private static final String ILLEGAL_FILENAME_CHARS_REGEX = "[/\\?%*:|\"'<>.]";

  /**
   * Encodes the given string by removing chars which are illegal on most file systems.
   *
   * @param string the string to encode.
   * @return an encoded filename string.
   */
  public static String filenameEncode(String string) {
    if (string != null) {
      string = string.replaceAll(ILLEGAL_FILENAME_CHARS_REGEX, "");

      if (string.length() > 255) {
        string = string.substring(0, 255);
      }
    }

    return string;
  }

  /**
   * Returns a basic authentication string which is generated by prepending "Basic " and
   * base64-encoding username:password.
   *
   * @param username the username to use for authentication.
   * @param password the password to use for authentication.
   * @return the encoded string.
   */
  public static String getBasicAuthString(String username, String password) {
    String string = username + ":" + password;

    return "Basic " + Base64.getEncoder().encodeToString(string.getBytes());
  }
}
